# Generated by Django 2.2 on 2020-04-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pastors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jlm_ministry/')),
                ('full_name', models.CharField(max_length=250)),
                ('branch', models.CharField(choices=[('MAIN', 'Main branch'), ('KITENGELA', 'Kitengela branch'), ('KIBRA', 'Kibra')], default='branch', max_length=100)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
    ]
