# Generated by Django 2.2 on 2020-04-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0002_auto_20200419_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/'),
        ),
    ]
