# Generated by Django 2.2 on 2020-04-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0004_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bishop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/photos/')),
                ('full_name', models.CharField(max_length=250)),
                ('branch', models.CharField(choices=[('MAIN', 'Main branch'), ('KITENGELA', 'Kitengela branch'), ('KIBRA', 'Kibra')], default='branch', max_length=100)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
    ]
