# Generated by Django 2.2 on 2020-04-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0005_bishop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bishop',
            name='branch',
            field=models.CharField(choices=[('MAIN BRANCH', 'MAIN BRANCH'), ('KITENGELA BRANCH', 'KITENGELA BRANCH'), ('KIBRA BRANCH', 'KIBRA BRANCH')], default='branch', max_length=100),
        ),
    ]
