# Generated by Django 2.2 on 2020-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0006_auto_20200420_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastors',
            name='branch',
            field=models.CharField(choices=[('MAIN BRANCH', 'MAIN BRANCH'), ('KITENGELA BRANCH', 'KITENGELA BRANCH'), ('KIBRA BRANCH', 'KIBRA BRANCH')], default='branch', max_length=100),
        ),
    ]
