# Generated by Django 2.2 on 2020-04-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0007_auto_20200420_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastors',
            name='level',
            field=models.CharField(choices=[('Seniro Pastor', 'Seniro Pastor'), ('Pastor', 'Pastor')], default='level', max_length=100),
        ),
    ]
