# Generated by Django 2.2 on 2020-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0009_auto_20200420_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bishop',
            name='branch',
            field=models.CharField(choices=[('Main branch', 'Main branch'), ('Kitengela branch', 'Kitengela branch'), ('Kibera branch', 'Kibera branch'), ('Visionary', 'Visionary')], default='branch', max_length=100),
        ),
    ]
