# Generated by Django 2.2 on 2020-04-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0010_auto_20200420_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bishop',
            name='branch',
            field=models.CharField(choices=[('Main branch', 'Main branch'), ('Kitengela branch', 'Kitengela branch'), ('Kibera branch', 'Kibera branch'), ('Jlm ministries', 'Jlm ministries')], default='branch', max_length=100),
        ),
        migrations.AlterField(
            model_name='pastors',
            name='level',
            field=models.CharField(choices=[('Senior Pastor', 'Senior Pastor'), ('Pastor', 'Pastor')], default='level', max_length=100),
        ),
    ]
