# Generated by Django 2.2 on 2020-04-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0013_auto_20200421_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='level',
            field=models.CharField(choices=[('Senior Pastor', 'Senior Pastor'), ('Pastor', 'Pastor')], default='level', max_length=100),
        ),
    ]
