# Generated by Django 2.2 on 2020-04-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0014_chairman_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chairman',
        ),
    ]
