# Generated by Django 2.2 on 2020-04-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0015_delete_chairman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/photos/')),
                ('full_name', models.CharField(max_length=250)),
                ('branch', models.CharField(choices=[('Main branch', 'Main branch'), ('Kitengela branch', 'Kitengela branch'), ('Kibera branch', 'Kibera branch'), ('Jlm ministries', 'Jlm ministries')], default='branch', max_length=100)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
    ]
