# Generated by Django 2.2 on 2020-04-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0016_leadership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bishop',
        ),
        migrations.AddField(
            model_name='leadership',
            name='level',
            field=models.CharField(choices=[('Senior Pastor', 'Senior Pastor'), ('Pastor', 'Pastor')], default='level', max_length=100),
        ),
    ]
