# Generated by Django 2.2 on 2020-04-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0017_auto_20200421_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='branch',
            field=models.CharField(choices=[('Bishop of jlm ministries', 'Bishop of jlm ministries'), ('Kitengela branch', 'Kitengela branch'), ('Kibera branch', 'Kibera branch'), ('Jlm ministries', 'Jlm ministries')], default='branch', max_length=100),
        ),
    ]
