# Generated by Django 2.2 on 2020-04-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0019_auto_20200421_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='level',
            field=models.CharField(choices=[('Senior Pastor', 'Senior Pastor'), ('Pastor', 'Pastor'), ('Bishop', 'Bishop')], default='level', max_length=100),
        ),
    ]
