# Generated by Django 2.2 on 2020-04-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0021_leadership_biograpgy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ushering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/photos/')),
                ('full_name', models.CharField(max_length=250)),
                ('branch', models.CharField(choices=[('Main branch', 'Main branch'), ('Kitengela branch', 'Kitengela branch'), ('Kibera branch', 'Kibera branch')], default='branch', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
