# Generated by Django 2.2 on 2020-04-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0023_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastors',
            name='level',
            field=models.CharField(choices=[('Senior Resident Pastor', 'Senior Resident Pastor'), ('Assistant Resident Pastor', 'Assistant Resident Pastor'), ('Pastor', 'Pastor')], default='level', max_length=100),
        ),
    ]
