# Generated by Django 2.2 on 2020-04-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0024_auto_20200422_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='ushering',
            name='level',
            field=models.CharField(choices=[('Head usher', 'Head Usher'), ('Usher', 'Usher')], default='level', max_length=100),
        ),
    ]
