# Generated by Django 2.2 on 2020-04-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0025_ushering_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worshipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/photos/')),
                ('full_name', models.CharField(max_length=250)),
                ('level', models.CharField(choices=[('Head Worshipper', 'Head Worshipper'), ('Worshipper', 'Worshipper')], default='level', max_length=100)),
                ('branch', models.CharField(choices=[('Main branch', 'Main branch'), ('Kitengela branch', 'Kitengela branch'), ('Kibera branch', 'Kibera branch')], default='branch', max_length=100)),
            ],
        ),
    ]
