# Generated by Django 2.2 on 2020-04-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0027_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='level',
            field=models.CharField(choices=[('Head of media', 'Head Wof media'), ('Media', 'Media')], default='level', max_length=100),
        ),
    ]
