# Generated by Django 2.2 on 2020-04-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlm_ministry', '0031_deacon'),
    ]

    operations = [
        migrations.AddField(
            model_name='deacon',
            name='level',
            field=models.CharField(choices=[('Deacon', 'Deacon'), ('Deaconnes', 'Deaconnes')], default='level', max_length=100),
        ),
    ]
